spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/TaskApplication"
    username: "ii"
    password: "ii"
    driver-class-name: "org.postgresql.Driver"
  data:
    jpa.repositories.enabled: true
